.TH XLOCKMOST 1 "13 January 2010" "0.2" "xlockmost manual page"
.SH NAME
xlockmost \- very simple x11 display locker.
.SH SYNOPSIS
.B xlockmost
[\fIoptions\fR]
.SH DESCRIPTION
.SH OPTIONS
.SS "Arguments:"
.TP
.BI \-h,\-\-help
Show this help screen
.TP
.BI \-v,\-\-version
print version number
.TP
.BI \-d,\-\-dpms\ \fIMODE:TIMEOUT[,MODE:TIMEOUT...]\fR
set dpms mode and timeout
.SH AUTHOR
xlockmost was written by
.nh
.ad l
Alexey Smirnov <alexey.smirnov@gmx.com>
.hy
.br
This manual page was prepared by
.nh
.ad l
Alexey Smirnov <alexey.smirnov@gmx.com>
.hy
for the Debian GNU/Linux system (but may be used by others).
